name = "Jade's Parity Plus"
author = "jadelily18"
version = "2.3.0+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dab238988c8d4f89f2291a2ae08181af21626ed9d61ea93686029bdf92aacc5e"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"

[options]
acceptable-game-versions = ["1.19.3", "1.19.4"]
